[package]
name = "AdventOfCode2015"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
md-5 = "0.10.5"
rayon = "1.7.0"
regex = "1.8.4"
